package com.email.backend.service.ai;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AIRouterTest {

    static class MockAIService implements AIService {
        private final String name;
        private final boolean shouldFail;

        public MockAIService(String name, boolean shouldFail) {
            this.name = name;
            this.shouldFail = shouldFail;
        }

        @Override
        public String getProviderName() {
            return name;
        }

        @Override
        public String generateDocumentation(String codeContext, String prompt) {
            if (shouldFail) {
                throw new RuntimeException(name + " service unavailable");
            }
            return "Doc generated by " + name;
        }

        @Override
        public String explainCode(String codeSnippet) {
            if (shouldFail) {
                throw new RuntimeException(name + " service unavailable");
            }
            return "Explanation by " + name;
        }

        @Override
        public String suggestImprovements(String codeSnippet) {
            if (shouldFail) {
                throw new RuntimeException(name + " service unavailable");
            }
            return "Suggestions by " + name;
        }
    }

    @Test
    void testPrimaryProviderSuccess() {
        AIService primary = new MockAIService("Gemini", false);
        AIService secondary = new MockAIService("Groq", false);
        AIRouter router = new AIRouter(List.of(primary, secondary));

        String result = router.generateDocumentation("class Foo {}", "prompt");
        assertEquals("Doc generated by Gemini", result);
    }

    @Test
    void testFallbackToSecondaryProviderWhenPrimaryFails() {
        AIService primary = new MockAIService("Gemini", true);
        AIService secondary = new MockAIService("Groq", false);
        AIRouter router = new AIRouter(List.of(primary, secondary));

        String doc = router.generateDocumentation("class Foo {}", "prompt");
        assertEquals("Doc generated by Groq", doc);

        String exp = router.explainCode("class Foo {}");
        assertEquals("Explanation by Groq", exp);

        String sug = router.suggestImprovements("class Foo {}");
        assertEquals("Suggestions by Groq", sug);
    }

    @Test
    void testAllProvidersFailThrowsException() {
        AIService primary = new MockAIService("Gemini", true);
        AIService secondary = new MockAIService("Groq", true);
        AIRouter router = new AIRouter(List.of(primary, secondary));

        RuntimeException exception = assertThrows(RuntimeException.class, () -> 
                router.generateDocumentation("class Foo {}", "prompt"));
        assertTrue(exception.getMessage().contains("All AI Service providers failed"));
    }
}
