spring.application.name=devdocs-backend
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=${NEO_USERNAME}
spring.neo4j.authentication.password=${NEO_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-milliseconds=86400000

ai.provider.gemini.enabled=true
ai.provider.groq.enabled=false

gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.5-flash-lite
spring.ai.vertex.ai.gemini.api-key=${GEMINI_API_KEY}
#spring.ai.openai.api-key=${GROQ_API_KEY:your_groq_api_key_here}
spring.ai.openai.base-url=https://api.groq.com/openai
